#!/usr/bin/env python3

import json
import sys

from feeding.feeding import get_feeding_result, Feeding


def main():
    json_feeding = json.load(sys.stdin)

    try:
        feeding = Feeding.from_json(json_feeding)
        result = get_feeding_result(feeding)
        print(json.dumps(result.to_json()))
    except:
        pass


if __name__ == '__main__':
    main()
