#!/usr/bin/env python3

import json
import sys
from itertools import takewhile


def run():
    buffer = ''
    count = 0

    for chars in takewhile(lambda s: s != '', sys.stdin):
        for char in chars.strip():
            buffer += char
            try:
                json.loads(buffer)
                print(buffer)

                buffer = ''
                count += 1

            except ValueError:
                pass

    print('{{"count": {}}}'.format(count))


if __name__ == '__main__':
    run()
