#!/usr/bin/env python3

import json
import sys

def run():
    buffer = ''
    count = 0

    while True:
        chars = sys.stdin.readline()
        if chars == '':
            break

        for char in chars.strip():
            buffer += char
            try:
                json.loads(buffer)
                print(buffer)

                buffer = ''
                count += 1

            except ValueError:
                pass

    print('{{"count": {}}}'.format(count))

if __name__ == '__main__':
    run()
